services:
  backend:
    image: ghcr.io/sidneyjunio-nerus/assinatura-nerus/backend:latest
    container_name: assinaturas-backend
    restart: unless-stopped
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      NODE_ENV: production
      TZ: ${TZ}
    ports:
      - "3001:3001"
    networks:
      - assinaturas
  frontend:
    image: ghcr.io/sidneyjunio-nerus/assinatura-nerus/frontend:latest
    container_name: assinaturas-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      TZ: ${TZ}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - assinaturas
networks:
  assinaturas:
    driver: bridge